### PR TITLE
Add expand option

### LINKED ISSUE #16: Add -e, --expand option; expands key numbers to key names
While key numbers are very nice for interactively transforming data they can change when the data changes.   So for non-interactive use such as scripts the user needs to use key names.  The purpose of the -e, --expand option is to allow the user to interactively transform data and then print the long version of the same command with any key numbers replaced with their respective key names.

### PR DESCRIPTION
**Pull request by hugoalvarado**
Fixes #16 

Add the expand (-e) option that will allow the user to print the long
version of the a given command with any key numbers replaced with
their respective key names.

### CODE REVIEW

**Comment by hugoalvarado** [comment]
Ready for review @bpeterso2000 :).

**Comment by bpeterso2000** [comment]
Thanks, looks good. ... just needs a fix to work with commands that do not include a '--root' option and I think it'll be ready to go.

Example:
`jsoncut -eg2 weather.json`

```
  File "c:\work\github\jsoncut\jsoncut\cli.py", line 70, in expand
    if not kwds['rootkey'].isdigit():
AttributeError: 'NoneType' object has no attribute 'isdigit'
```

**Comment by hugoalvarado** [comment]
Hello @bpeterso2000, should be working better now.

**Comment by bpeterso2000** [comment]
It's getting better, almost there ...
Using the test file located here https://github.com/json-transformations/jsoncore/blob/master/tests/data/beer.json

```
(jsoncut) C:\work\github\jsoncut>jsoncut \work\github\jsoncore\tests\data\beer.json -r 0.method.mash_temp
[
  {
    "temp": {
      "value": 64,
      "unit": "celsius"
    },
    "duration": 75
  }
]

(jsoncut) C:\work\github\jsoncut>jsoncut \work\github\jsoncore\tests\data\beer.json -r 0.method.mash_temp -e
KeyNotNumeric: 0.method.mash_temp
```

**Comment by hugoalvarado** [comment]
Ohh, so numeric indexes and non-numeric can be mixed to specify the root...
I will check that.

**Comment by bpeterso2000** [comment]
Thanks.  Here are some examples of JSON selectors from the README docs: 

1 | key #
.1 | key name
store | key name
store.book | key names
store.book.2 | key names w/ index
store.book.-1.price | key names /w index
store.book.:2 | key name /w slice

**Comment by hugoalvarado** [comment]
Can starting indexes and key #s be mixed?

For example using  quakes.json -r features.0.geometry I get 
```
{
  "type": "Point",
  "coordinates": [
    -117.8588333,
    36.5123333,
    -0.19
  ]
}
```
which corresponds to the data in the features key (which is a list) -> index 0 -> geometry key.

I can also get all features by using the list index (features is index 2 with -l).

Using quakes.json -r 2 (this is the same as quakes.json -r features) I can see all features,
but quakes.json -r 2.0.geometry returns nothing.

**Comment by bpeterso2000** [comment]
>> Using quakes.json -r 2 (this is the same as quakes.json -r features) I can see all features,
but quakes.json -r 2.0.geometry returns nothing.

No key #'s can't be mixed in this way.

**Comment by hugoalvarado** [comment]
@bpeterso2000 It looks like if the -r option is specified with any non-numeric value , it is already expanded. I make a change that seems to cover the cases of JSON selectors described above ⬆️ .

**Pull request merged**
